
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.zdemocds30cdsedmx.batch;

import com.sap.cloud.sdk.datamodel.odata.helper.batch.FluentHelperServiceBatch;


/**
 * Interface to the batch object of an {@code com.sap.cloud.sdk.tutorial.datamodel.odata.services.ZDEMOCDS30CDSEdmxService ZDEMOCDS30CDSEdmxService} service.
 * 
 */
public interface ZDEMOCDS30CDSEdmxServiceBatch
    extends FluentHelperServiceBatch<ZDEMOCDS30CDSEdmxServiceBatch, ZDEMOCDS30CDSEdmxServiceBatchChangeSet>
{


}
