
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner;

import java.time.LocalDateTime;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.cloudplatform.connectivity.Destination;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmEntity;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import com.sap.cloud.sdk.s4hana.datamodel.odata.annotation.Key;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.field.BPAddressIndependentPhoneField;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.selectable.BPAddressIndependentPhoneSelectable;
import com.sap.cloud.sdk.typeconverter.TypeConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * Address Independent Phone Number<p></p><p>Original entity name from the Odata EDM: <b>A_BPAddressIndependentPhoneType</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class BPAddressIndependentPhone
    extends VdmEntity<BPAddressIndependentPhone>
{

    /**
     * Selector for all available fields of BPAddressIndependentPhone.
     * 
     */
    public final static BPAddressIndependentPhoneSelectable ALL_FIELDS = () -> "*";
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>BusinessPartner</b></p>
     * 
     * @return
     *     Business Partner Number
     */
    @Key
    @SerializedName("BusinessPartner")
    @JsonProperty("BusinessPartner")
    @Nullable
    @ODataField(odataName = "BusinessPartner")
    private String businessPartner;
    /**
     * Use with available fluent helpers to apply the <b>BusinessPartner</b> field to query operations.
     * 
     */
    public final static BPAddressIndependentPhoneField<String> BUSINESS_PARTNER = new BPAddressIndependentPhoneField<String>("BusinessPartner");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>AddressID</b></p>
     * 
     * @return
     *     Address Number
     */
    @Key
    @SerializedName("AddressID")
    @JsonProperty("AddressID")
    @Nullable
    @ODataField(odataName = "AddressID")
    private String addressID;
    /**
     * Use with available fluent helpers to apply the <b>AddressID</b> field to query operations.
     * 
     */
    public final static BPAddressIndependentPhoneField<String> ADDRESS_ID = new BPAddressIndependentPhoneField<String>("AddressID");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>Person</b></p>
     * 
     * @return
     *     Person Number
     */
    @Key
    @SerializedName("Person")
    @JsonProperty("Person")
    @Nullable
    @ODataField(odataName = "Person")
    private String person;
    /**
     * Use with available fluent helpers to apply the <b>Person</b> field to query operations.
     * 
     */
    public final static BPAddressIndependentPhoneField<String> PERSON = new BPAddressIndependentPhoneField<String>("Person");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>OrdinalNumber</b></p>
     * 
     * @return
     *     Sequence Number
     */
    @Key
    @SerializedName("OrdinalNumber")
    @JsonProperty("OrdinalNumber")
    @Nullable
    @ODataField(odataName = "OrdinalNumber")
    private String ordinalNumber;
    /**
     * Use with available fluent helpers to apply the <b>OrdinalNumber</b> field to query operations.
     * 
     */
    public final static BPAddressIndependentPhoneField<String> ORDINAL_NUMBER = new BPAddressIndependentPhoneField<String>("OrdinalNumber");
    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>DestinationLocationCountry</b></p>
     * 
     * @return
     *     Country/Region for Telephone/Fax Number
     */
    @SerializedName("DestinationLocationCountry")
    @JsonProperty("DestinationLocationCountry")
    @Nullable
    @ODataField(odataName = "DestinationLocationCountry")
    private String destinationLocationCountry;
    /**
     * Use with available fluent helpers to apply the <b>DestinationLocationCountry</b> field to query operations.
     * 
     */
    public final static BPAddressIndependentPhoneField<String> DESTINATION_LOCATION_COUNTRY = new BPAddressIndependentPhoneField<String>("DestinationLocationCountry");
    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>InternationalPhoneNumber</b></p>
     * 
     * @return
     *     Complete Number: Dialing Code+Number+Extension
     */
    @SerializedName("InternationalPhoneNumber")
    @JsonProperty("InternationalPhoneNumber")
    @Nullable
    @ODataField(odataName = "InternationalPhoneNumber")
    private String internationalPhoneNumber;
    /**
     * Use with available fluent helpers to apply the <b>InternationalPhoneNumber</b> field to query operations.
     * 
     */
    public final static BPAddressIndependentPhoneField<String> INTERNATIONAL_PHONE_NUMBER = new BPAddressIndependentPhoneField<String>("InternationalPhoneNumber");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>IsDefaultPhoneNumber</b></p>
     * 
     * @return
     *     Data element for domain BOOLE: TRUE (='X') and FALSE (=' ')
     */
    @SerializedName("IsDefaultPhoneNumber")
    @JsonProperty("IsDefaultPhoneNumber")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "IsDefaultPhoneNumber")
    private Boolean isDefaultPhoneNumber;
    /**
     * Use with available fluent helpers to apply the <b>IsDefaultPhoneNumber</b> field to query operations.
     * 
     */
    public final static BPAddressIndependentPhoneField<Boolean> IS_DEFAULT_PHONE_NUMBER = new BPAddressIndependentPhoneField<Boolean>("IsDefaultPhoneNumber");
    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>PhoneNumber</b></p>
     * 
     * @return
     *     Telephone No.: Dialing Code and Number
     */
    @SerializedName("PhoneNumber")
    @JsonProperty("PhoneNumber")
    @Nullable
    @ODataField(odataName = "PhoneNumber")
    private String phoneNumber;
    /**
     * Use with available fluent helpers to apply the <b>PhoneNumber</b> field to query operations.
     * 
     */
    public final static BPAddressIndependentPhoneField<String> PHONE_NUMBER = new BPAddressIndependentPhoneField<String>("PhoneNumber");
    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>PhoneNumberExtension</b></p>
     * 
     * @return
     *     Telephone no.: Extension
     */
    @SerializedName("PhoneNumberExtension")
    @JsonProperty("PhoneNumberExtension")
    @Nullable
    @ODataField(odataName = "PhoneNumberExtension")
    private String phoneNumberExtension;
    /**
     * Use with available fluent helpers to apply the <b>PhoneNumberExtension</b> field to query operations.
     * 
     */
    public final static BPAddressIndependentPhoneField<String> PHONE_NUMBER_EXTENSION = new BPAddressIndependentPhoneField<String>("PhoneNumberExtension");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>PhoneNumberType</b></p>
     * 
     * @return
     *     Phone Number Type
     */
    @SerializedName("PhoneNumberType")
    @JsonProperty("PhoneNumberType")
    @Nullable
    @ODataField(odataName = "PhoneNumberType")
    private String phoneNumberType;
    /**
     * Use with available fluent helpers to apply the <b>PhoneNumberType</b> field to query operations.
     * 
     */
    public final static BPAddressIndependentPhoneField<String> PHONE_NUMBER_TYPE = new BPAddressIndependentPhoneField<String>("PhoneNumberType");
    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>ValidityStartDate</b></p>
     * 
     * @return
     *     The validityStartDate contained in this entity.
     */
    @SerializedName("ValidityStartDate")
    @JsonProperty("ValidityStartDate")
    @Nullable
    @JsonSerialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeSerializer.class)
    @JsonDeserialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeDeserializer.class)
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeAdapter.class)
    @ODataField(odataName = "ValidityStartDate", converter = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeCalendarConverter.class)
    private LocalDateTime validityStartDate;
    /**
     * Use with available fluent helpers to apply the <b>ValidityStartDate</b> field to query operations.
     * 
     */
    public final static BPAddressIndependentPhoneField<LocalDateTime> VALIDITY_START_DATE = new BPAddressIndependentPhoneField<LocalDateTime>("ValidityStartDate");
    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>ValidityEndDate</b></p>
     * 
     * @return
     *     The validityEndDate contained in this entity.
     */
    @SerializedName("ValidityEndDate")
    @JsonProperty("ValidityEndDate")
    @Nullable
    @JsonSerialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeSerializer.class)
    @JsonDeserialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeDeserializer.class)
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeAdapter.class)
    @ODataField(odataName = "ValidityEndDate", converter = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeCalendarConverter.class)
    private LocalDateTime validityEndDate;
    /**
     * Use with available fluent helpers to apply the <b>ValidityEndDate</b> field to query operations.
     * 
     */
    public final static BPAddressIndependentPhoneField<LocalDateTime> VALIDITY_END_DATE = new BPAddressIndependentPhoneField<LocalDateTime>("ValidityEndDate");

    @Nonnull
    @Override
    public Class<BPAddressIndependentPhone> getType() {
        return BPAddressIndependentPhone.class;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>BusinessPartner</b></p>
     * 
     * @param businessPartner
     *     Business Partner Number
     */
    public void setBusinessPartner(
        @Nullable
        final String businessPartner) {
        rememberChangedField("BusinessPartner", this.businessPartner);
        this.businessPartner = businessPartner;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>AddressID</b></p>
     * 
     * @param addressID
     *     Address Number
     */
    public void setAddressID(
        @Nullable
        final String addressID) {
        rememberChangedField("AddressID", this.addressID);
        this.addressID = addressID;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>Person</b></p>
     * 
     * @param person
     *     Person Number
     */
    public void setPerson(
        @Nullable
        final String person) {
        rememberChangedField("Person", this.person);
        this.person = person;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>OrdinalNumber</b></p>
     * 
     * @param ordinalNumber
     *     Sequence Number
     */
    public void setOrdinalNumber(
        @Nullable
        final String ordinalNumber) {
        rememberChangedField("OrdinalNumber", this.ordinalNumber);
        this.ordinalNumber = ordinalNumber;
    }

    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>DestinationLocationCountry</b></p>
     * 
     * @param destinationLocationCountry
     *     Country/Region for Telephone/Fax Number
     */
    public void setDestinationLocationCountry(
        @Nullable
        final String destinationLocationCountry) {
        rememberChangedField("DestinationLocationCountry", this.destinationLocationCountry);
        this.destinationLocationCountry = destinationLocationCountry;
    }

    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>InternationalPhoneNumber</b></p>
     * 
     * @param internationalPhoneNumber
     *     Complete Number: Dialing Code+Number+Extension
     */
    public void setInternationalPhoneNumber(
        @Nullable
        final String internationalPhoneNumber) {
        rememberChangedField("InternationalPhoneNumber", this.internationalPhoneNumber);
        this.internationalPhoneNumber = internationalPhoneNumber;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>IsDefaultPhoneNumber</b></p>
     * 
     * @param isDefaultPhoneNumber
     *     Data element for domain BOOLE: TRUE (='X') and FALSE (=' ')
     */
    public void setIsDefaultPhoneNumber(
        @Nullable
        final Boolean isDefaultPhoneNumber) {
        rememberChangedField("IsDefaultPhoneNumber", this.isDefaultPhoneNumber);
        this.isDefaultPhoneNumber = isDefaultPhoneNumber;
    }

    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>PhoneNumber</b></p>
     * 
     * @param phoneNumber
     *     Telephone No.: Dialing Code and Number
     */
    public void setPhoneNumber(
        @Nullable
        final String phoneNumber) {
        rememberChangedField("PhoneNumber", this.phoneNumber);
        this.phoneNumber = phoneNumber;
    }

    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>PhoneNumberExtension</b></p>
     * 
     * @param phoneNumberExtension
     *     Telephone no.: Extension
     */
    public void setPhoneNumberExtension(
        @Nullable
        final String phoneNumberExtension) {
        rememberChangedField("PhoneNumberExtension", this.phoneNumberExtension);
        this.phoneNumberExtension = phoneNumberExtension;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>PhoneNumberType</b></p>
     * 
     * @param phoneNumberType
     *     Phone Number Type
     */
    public void setPhoneNumberType(
        @Nullable
        final String phoneNumberType) {
        rememberChangedField("PhoneNumberType", this.phoneNumberType);
        this.phoneNumberType = phoneNumberType;
    }

    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>ValidityStartDate</b></p>
     * 
     * @param validityStartDate
     *     The validityStartDate to set.
     */
    public void setValidityStartDate(
        @Nullable
        final LocalDateTime validityStartDate) {
        rememberChangedField("ValidityStartDate", this.validityStartDate);
        this.validityStartDate = validityStartDate;
    }

    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>ValidityEndDate</b></p>
     * 
     * @param validityEndDate
     *     The validityEndDate to set.
     */
    public void setValidityEndDate(
        @Nullable
        final LocalDateTime validityEndDate) {
        rememberChangedField("ValidityEndDate", this.validityEndDate);
        this.validityEndDate = validityEndDate;
    }

    @Override
    protected String getEntityCollection() {
        return "A_BPAddressIndependentPhone";
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        result.put("BusinessPartner", getBusinessPartner());
        result.put("AddressID", getAddressID());
        result.put("Person", getPerson());
        result.put("OrdinalNumber", getOrdinalNumber());
        return result;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("BusinessPartner", getBusinessPartner());
        values.put("AddressID", getAddressID());
        values.put("Person", getPerson());
        values.put("OrdinalNumber", getOrdinalNumber());
        values.put("DestinationLocationCountry", getDestinationLocationCountry());
        values.put("InternationalPhoneNumber", getInternationalPhoneNumber());
        values.put("IsDefaultPhoneNumber", getIsDefaultPhoneNumber());
        values.put("PhoneNumber", getPhoneNumber());
        values.put("PhoneNumberExtension", getPhoneNumberExtension());
        values.put("PhoneNumberType", getPhoneNumberType());
        values.put("ValidityStartDate", getValidityStartDate());
        values.put("ValidityEndDate", getValidityEndDate());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("BusinessPartner")) {
                final Object value = values.remove("BusinessPartner");
                if ((value == null)||(!value.equals(getBusinessPartner()))) {
                    setBusinessPartner(((String) value));
                }
            }
            if (values.containsKey("AddressID")) {
                final Object value = values.remove("AddressID");
                if ((value == null)||(!value.equals(getAddressID()))) {
                    setAddressID(((String) value));
                }
            }
            if (values.containsKey("Person")) {
                final Object value = values.remove("Person");
                if ((value == null)||(!value.equals(getPerson()))) {
                    setPerson(((String) value));
                }
            }
            if (values.containsKey("OrdinalNumber")) {
                final Object value = values.remove("OrdinalNumber");
                if ((value == null)||(!value.equals(getOrdinalNumber()))) {
                    setOrdinalNumber(((String) value));
                }
            }
            if (values.containsKey("DestinationLocationCountry")) {
                final Object value = values.remove("DestinationLocationCountry");
                if ((value == null)||(!value.equals(getDestinationLocationCountry()))) {
                    setDestinationLocationCountry(((String) value));
                }
            }
            if (values.containsKey("InternationalPhoneNumber")) {
                final Object value = values.remove("InternationalPhoneNumber");
                if ((value == null)||(!value.equals(getInternationalPhoneNumber()))) {
                    setInternationalPhoneNumber(((String) value));
                }
            }
            if (values.containsKey("IsDefaultPhoneNumber")) {
                final Object value = values.remove("IsDefaultPhoneNumber");
                if ((value == null)||(!value.equals(getIsDefaultPhoneNumber()))) {
                    setIsDefaultPhoneNumber(((Boolean) value));
                }
            }
            if (values.containsKey("PhoneNumber")) {
                final Object value = values.remove("PhoneNumber");
                if ((value == null)||(!value.equals(getPhoneNumber()))) {
                    setPhoneNumber(((String) value));
                }
            }
            if (values.containsKey("PhoneNumberExtension")) {
                final Object value = values.remove("PhoneNumberExtension");
                if ((value == null)||(!value.equals(getPhoneNumberExtension()))) {
                    setPhoneNumberExtension(((String) value));
                }
            }
            if (values.containsKey("PhoneNumberType")) {
                final Object value = values.remove("PhoneNumberType");
                if ((value == null)||(!value.equals(getPhoneNumberType()))) {
                    setPhoneNumberType(((String) value));
                }
            }
            if (values.containsKey("ValidityStartDate")) {
                final Object value = values.remove("ValidityStartDate");
                if ((value == null)||(!value.equals(getValidityStartDate()))) {
                    setValidityStartDate(((LocalDateTime) value));
                }
            }
            if (values.containsKey("ValidityEndDate")) {
                final Object value = values.remove("ValidityEndDate");
                if ((value == null)||(!value.equals(getValidityEndDate()))) {
                    setValidityEndDate(((LocalDateTime) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param fieldType
     *     The Java type to use for the extension field when performing value comparisons.
     * @return
     *     A representation of an extension field from this entity.
     */
    @Nonnull
    public static<T >BPAddressIndependentPhoneField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final Class<T> fieldType) {
        return new BPAddressIndependentPhoneField<T>(fieldName);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param typeConverter
     *     A TypeConverter<T, DomainT> instance whose first generic type matches the Java type of the field
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param <DomainT>
     *     The type of the extension field as returned by the OData service.
     * @return
     *     A representation of an extension field from this entity, holding a reference to the given TypeConverter.
     */
    @Nonnull
    public static<T,DomainT >BPAddressIndependentPhoneField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final TypeConverter<T, DomainT> typeConverter) {
        return new BPAddressIndependentPhoneField<T>(fieldName, typeConverter);
    }

    @Override
    @Nullable
    public Destination getDestinationForFetch() {
        return super.getDestinationForFetch();
    }

    @Override
    protected void setServicePathForFetch(
        @Nullable
        final String servicePathForFetch) {
        super.setServicePathForFetch(servicePathForFetch);
    }

    @Override
    public void attachToService(
        @Nullable
        final String servicePath,
        @Nonnull
        final Destination destination) {
        super.attachToService(servicePath, destination);
    }

    @Override
    protected String getDefaultServicePath() {
        return (com.sap.cloud.sdk.tutorial.datamodel.odata.services.BusinessPartnerService.DEFAULT_SERVICE_PATH);
    }

}
