
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner;

import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.cloudplatform.connectivity.Destination;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmEntity;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import com.sap.cloud.sdk.s4hana.datamodel.odata.annotation.Key;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.field.BPDataControllerField;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.selectable.BPDataControllerSelectable;
import com.sap.cloud.sdk.typeconverter.TypeConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * Business Partner Data Controller<p></p><p>Original entity name from the Odata EDM: <b>A_BPDataControllerType</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class BPDataController
    extends VdmEntity<BPDataController>
{

    /**
     * Selector for all available fields of BPDataController.
     * 
     */
    public final static BPDataControllerSelectable ALL_FIELDS = () -> "*";
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>BusinessPartner</b></p>
     * 
     * @return
     *     Business Partner Number
     */
    @Key
    @SerializedName("BusinessPartner")
    @JsonProperty("BusinessPartner")
    @Nullable
    @ODataField(odataName = "BusinessPartner")
    private String businessPartner;
    /**
     * Use with available fluent helpers to apply the <b>BusinessPartner</b> field to query operations.
     * 
     */
    public final static BPDataControllerField<String> BUSINESS_PARTNER = new BPDataControllerField<String>("BusinessPartner");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>DataController</b></p>
     * 
     * @return
     *     BP: Data Controller
     */
    @Key
    @SerializedName("DataController")
    @JsonProperty("DataController")
    @Nullable
    @ODataField(odataName = "DataController")
    private String dataController;
    /**
     * Use with available fluent helpers to apply the <b>DataController</b> field to query operations.
     * 
     */
    public final static BPDataControllerField<String> DATA_CONTROLLER = new BPDataControllerField<String>("DataController");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>PurposeForPersonalData</b></p>
     * 
     * @return
     *     BP: Purpose
     */
    @Key
    @SerializedName("PurposeForPersonalData")
    @JsonProperty("PurposeForPersonalData")
    @Nullable
    @ODataField(odataName = "PurposeForPersonalData")
    private String purposeForPersonalData;
    /**
     * Use with available fluent helpers to apply the <b>PurposeForPersonalData</b> field to query operations.
     * 
     */
    public final static BPDataControllerField<String> PURPOSE_FOR_PERSONAL_DATA = new BPDataControllerField<String>("PurposeForPersonalData");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>DataControlAssignmentStatus</b></p>
     * 
     * @return
     *     BP: Data Controller Purpose Assignment Status
     */
    @SerializedName("DataControlAssignmentStatus")
    @JsonProperty("DataControlAssignmentStatus")
    @Nullable
    @ODataField(odataName = "DataControlAssignmentStatus")
    private String dataControlAssignmentStatus;
    /**
     * Use with available fluent helpers to apply the <b>DataControlAssignmentStatus</b> field to query operations.
     * 
     */
    public final static BPDataControllerField<String> DATA_CONTROL_ASSIGNMENT_STATUS = new BPDataControllerField<String>("DataControlAssignmentStatus");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BPDataControllerIsDerived</b></p>
     * 
     * @return
     *     BP: Derivation Indicator for Data Controller (DC)
     */
    @SerializedName("BPDataControllerIsDerived")
    @JsonProperty("BPDataControllerIsDerived")
    @Nullable
    @ODataField(odataName = "BPDataControllerIsDerived")
    private String bPDataControllerIsDerived;
    /**
     * Use with available fluent helpers to apply the <b>BPDataControllerIsDerived</b> field to query operations.
     * 
     */
    public final static BPDataControllerField<String> BP_DATA_CONTROLLER_IS_DERIVED = new BPDataControllerField<String>("BPDataControllerIsDerived");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>PurposeDerived</b></p>
     * 
     * @return
     *     BP: Derivation Indicator for Purpose
     */
    @SerializedName("PurposeDerived")
    @JsonProperty("PurposeDerived")
    @Nullable
    @ODataField(odataName = "PurposeDerived")
    private String purposeDerived;
    /**
     * Use with available fluent helpers to apply the <b>PurposeDerived</b> field to query operations.
     * 
     */
    public final static BPDataControllerField<String> PURPOSE_DERIVED = new BPDataControllerField<String>("PurposeDerived");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>PurposeType</b></p>
     * 
     * @return
     *     BP: Purpose Type
     */
    @SerializedName("PurposeType")
    @JsonProperty("PurposeType")
    @Nullable
    @ODataField(odataName = "PurposeType")
    private String purposeType;
    /**
     * Use with available fluent helpers to apply the <b>PurposeType</b> field to query operations.
     * 
     */
    public final static BPDataControllerField<String> PURPOSE_TYPE = new BPDataControllerField<String>("PurposeType");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BusinessPurposeFlag</b></p>
     * 
     * @return
     *     Business Purpose Completed Flag
     */
    @SerializedName("BusinessPurposeFlag")
    @JsonProperty("BusinessPurposeFlag")
    @Nullable
    @ODataField(odataName = "BusinessPurposeFlag")
    private String businessPurposeFlag;
    /**
     * Use with available fluent helpers to apply the <b>BusinessPurposeFlag</b> field to query operations.
     * 
     */
    public final static BPDataControllerField<String> BUSINESS_PURPOSE_FLAG = new BPDataControllerField<String>("BusinessPurposeFlag");

    @Nonnull
    @Override
    public Class<BPDataController> getType() {
        return BPDataController.class;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>BusinessPartner</b></p>
     * 
     * @param businessPartner
     *     Business Partner Number
     */
    public void setBusinessPartner(
        @Nullable
        final String businessPartner) {
        rememberChangedField("BusinessPartner", this.businessPartner);
        this.businessPartner = businessPartner;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>DataController</b></p>
     * 
     * @param dataController
     *     BP: Data Controller
     */
    public void setDataController(
        @Nullable
        final String dataController) {
        rememberChangedField("DataController", this.dataController);
        this.dataController = dataController;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>PurposeForPersonalData</b></p>
     * 
     * @param purposeForPersonalData
     *     BP: Purpose
     */
    public void setPurposeForPersonalData(
        @Nullable
        final String purposeForPersonalData) {
        rememberChangedField("PurposeForPersonalData", this.purposeForPersonalData);
        this.purposeForPersonalData = purposeForPersonalData;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>DataControlAssignmentStatus</b></p>
     * 
     * @param dataControlAssignmentStatus
     *     BP: Data Controller Purpose Assignment Status
     */
    public void setDataControlAssignmentStatus(
        @Nullable
        final String dataControlAssignmentStatus) {
        rememberChangedField("DataControlAssignmentStatus", this.dataControlAssignmentStatus);
        this.dataControlAssignmentStatus = dataControlAssignmentStatus;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BPDataControllerIsDerived</b></p>
     * 
     * @param bPDataControllerIsDerived
     *     BP: Derivation Indicator for Data Controller (DC)
     */
    public void setBPDataControllerIsDerived(
        @Nullable
        final String bPDataControllerIsDerived) {
        rememberChangedField("BPDataControllerIsDerived", this.bPDataControllerIsDerived);
        this.bPDataControllerIsDerived = bPDataControllerIsDerived;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>PurposeDerived</b></p>
     * 
     * @param purposeDerived
     *     BP: Derivation Indicator for Purpose
     */
    public void setPurposeDerived(
        @Nullable
        final String purposeDerived) {
        rememberChangedField("PurposeDerived", this.purposeDerived);
        this.purposeDerived = purposeDerived;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>PurposeType</b></p>
     * 
     * @param purposeType
     *     BP: Purpose Type
     */
    public void setPurposeType(
        @Nullable
        final String purposeType) {
        rememberChangedField("PurposeType", this.purposeType);
        this.purposeType = purposeType;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BusinessPurposeFlag</b></p>
     * 
     * @param businessPurposeFlag
     *     Business Purpose Completed Flag
     */
    public void setBusinessPurposeFlag(
        @Nullable
        final String businessPurposeFlag) {
        rememberChangedField("BusinessPurposeFlag", this.businessPurposeFlag);
        this.businessPurposeFlag = businessPurposeFlag;
    }

    @Override
    protected String getEntityCollection() {
        return "A_BPDataController";
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        result.put("BusinessPartner", getBusinessPartner());
        result.put("DataController", getDataController());
        result.put("PurposeForPersonalData", getPurposeForPersonalData());
        return result;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("BusinessPartner", getBusinessPartner());
        values.put("DataController", getDataController());
        values.put("PurposeForPersonalData", getPurposeForPersonalData());
        values.put("DataControlAssignmentStatus", getDataControlAssignmentStatus());
        values.put("BPDataControllerIsDerived", getBPDataControllerIsDerived());
        values.put("PurposeDerived", getPurposeDerived());
        values.put("PurposeType", getPurposeType());
        values.put("BusinessPurposeFlag", getBusinessPurposeFlag());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("BusinessPartner")) {
                final Object value = values.remove("BusinessPartner");
                if ((value == null)||(!value.equals(getBusinessPartner()))) {
                    setBusinessPartner(((String) value));
                }
            }
            if (values.containsKey("DataController")) {
                final Object value = values.remove("DataController");
                if ((value == null)||(!value.equals(getDataController()))) {
                    setDataController(((String) value));
                }
            }
            if (values.containsKey("PurposeForPersonalData")) {
                final Object value = values.remove("PurposeForPersonalData");
                if ((value == null)||(!value.equals(getPurposeForPersonalData()))) {
                    setPurposeForPersonalData(((String) value));
                }
            }
            if (values.containsKey("DataControlAssignmentStatus")) {
                final Object value = values.remove("DataControlAssignmentStatus");
                if ((value == null)||(!value.equals(getDataControlAssignmentStatus()))) {
                    setDataControlAssignmentStatus(((String) value));
                }
            }
            if (values.containsKey("BPDataControllerIsDerived")) {
                final Object value = values.remove("BPDataControllerIsDerived");
                if ((value == null)||(!value.equals(getBPDataControllerIsDerived()))) {
                    setBPDataControllerIsDerived(((String) value));
                }
            }
            if (values.containsKey("PurposeDerived")) {
                final Object value = values.remove("PurposeDerived");
                if ((value == null)||(!value.equals(getPurposeDerived()))) {
                    setPurposeDerived(((String) value));
                }
            }
            if (values.containsKey("PurposeType")) {
                final Object value = values.remove("PurposeType");
                if ((value == null)||(!value.equals(getPurposeType()))) {
                    setPurposeType(((String) value));
                }
            }
            if (values.containsKey("BusinessPurposeFlag")) {
                final Object value = values.remove("BusinessPurposeFlag");
                if ((value == null)||(!value.equals(getBusinessPurposeFlag()))) {
                    setBusinessPurposeFlag(((String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param fieldType
     *     The Java type to use for the extension field when performing value comparisons.
     * @return
     *     A representation of an extension field from this entity.
     */
    @Nonnull
    public static<T >BPDataControllerField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final Class<T> fieldType) {
        return new BPDataControllerField<T>(fieldName);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param typeConverter
     *     A TypeConverter<T, DomainT> instance whose first generic type matches the Java type of the field
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param <DomainT>
     *     The type of the extension field as returned by the OData service.
     * @return
     *     A representation of an extension field from this entity, holding a reference to the given TypeConverter.
     */
    @Nonnull
    public static<T,DomainT >BPDataControllerField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final TypeConverter<T, DomainT> typeConverter) {
        return new BPDataControllerField<T>(fieldName, typeConverter);
    }

    @Override
    @Nullable
    public Destination getDestinationForFetch() {
        return super.getDestinationForFetch();
    }

    @Override
    protected void setServicePathForFetch(
        @Nullable
        final String servicePathForFetch) {
        super.setServicePathForFetch(servicePathForFetch);
    }

    @Override
    public void attachToService(
        @Nullable
        final String servicePath,
        @Nonnull
        final Destination destination) {
        super.attachToService(servicePath, destination);
    }

    @Override
    protected String getDefaultServicePath() {
        return (com.sap.cloud.sdk.tutorial.datamodel.odata.services.BusinessPartnerService.DEFAULT_SERVICE_PATH);
    }

}
