
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.selectable;

import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentMobile;


/**
 * Interface to enable OData entity selectors for {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentMobile BPAddressIndependentMobile}. This interface is used by {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.field.BPAddressIndependentMobileField BPAddressIndependentMobileField} and {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.link.BPAddressIndependentMobileLink BPAddressIndependentMobileLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentMobile#BUSINESS_PARTNER BUSINESS_PARTNER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentMobile#ADDRESS_ID ADDRESS_ID}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentMobile#PERSON PERSON}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentMobile#ORDINAL_NUMBER ORDINAL_NUMBER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentMobile#INTERNATIONAL_PHONE_NUMBER INTERNATIONAL_PHONE_NUMBER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentMobile#IS_DEFAULT_PHONE_NUMBER IS_DEFAULT_PHONE_NUMBER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentMobile#MOBILE_PHONE_COUNTRY MOBILE_PHONE_COUNTRY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentMobile#MOBILE_PHONE_NUMBER MOBILE_PHONE_NUMBER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentMobile#PHONE_NUMBER_EXTENSION PHONE_NUMBER_EXTENSION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentMobile#PHONE_NUMBER_TYPE PHONE_NUMBER_TYPE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentMobile#VALIDITY_START_DATE VALIDITY_START_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentMobile#VALIDITY_END_DATE VALIDITY_END_DATE}</li>
 * </ul>
 * 
 */
public interface BPAddressIndependentMobileSelectable
    extends EntitySelectable<BPAddressIndependentMobile>
{


}
