
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.selectable;

import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentEmail;


/**
 * Interface to enable OData entity selectors for {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentEmail BPAddressIndependentEmail}. This interface is used by {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.field.BPAddressIndependentEmailField BPAddressIndependentEmailField} and {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.link.BPAddressIndependentEmailLink BPAddressIndependentEmailLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentEmail#BUSINESS_PARTNER BUSINESS_PARTNER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentEmail#ADDRESS_ID ADDRESS_ID}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentEmail#PERSON PERSON}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentEmail#ORDINAL_NUMBER ORDINAL_NUMBER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentEmail#EMAIL_ADDRESS EMAIL_ADDRESS}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentEmail#IS_DEFAULT_EMAIL_ADDRESS IS_DEFAULT_EMAIL_ADDRESS}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentEmail#VALIDITY_START_DATE VALIDITY_START_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPAddressIndependentEmail#VALIDITY_END_DATE VALIDITY_END_DATE}</li>
 * </ul>
 * 
 */
public interface BPAddressIndependentEmailSelectable
    extends EntitySelectable<BPAddressIndependentEmail>
{


}
