
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.selectable;

import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion;


/**
 * Interface to enable OData entity selectors for {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion BPIntlAddressVersion}. This interface is used by {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.field.BPIntlAddressVersionField BPIntlAddressVersionField} and {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.link.BPIntlAddressVersionLink BPIntlAddressVersionLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#BUSINESS_PARTNER BUSINESS_PARTNER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#ADDRESS_ID ADDRESS_ID}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#ADDRESS_REPRESENTATION_CODE ADDRESS_REPRESENTATION_CODE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#ADDRESSEE_FULL_NAME ADDRESSEE_FULL_NAME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#ADDRESS_ID_BY_EXTERNAL_SYSTEM ADDRESS_ID_BY_EXTERNAL_SYSTEM}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#ADDRESS_PERSON_ID ADDRESS_PERSON_ID}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#ADDRESS_SEARCH_TERM1 ADDRESS_SEARCH_TERM1}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#ADDRESS_SEARCH_TERM2 ADDRESS_SEARCH_TERM2}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#ADDRESS_TIME_ZONE ADDRESS_TIME_ZONE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#CARE_OF_NAME CARE_OF_NAME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#CITY_NAME CITY_NAME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#CITY_NUMBER CITY_NUMBER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#COMPANY_POSTAL_CODE COMPANY_POSTAL_CODE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#COUNTRY COUNTRY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#DELIVERY_SERVICE_NUMBER DELIVERY_SERVICE_NUMBER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#DELIVERY_SERVICE_TYPE_CODE DELIVERY_SERVICE_TYPE_CODE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#DISTRICT_NAME DISTRICT_NAME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#FORM_OF_ADDRESS FORM_OF_ADDRESS}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#HOUSE_NUMBER HOUSE_NUMBER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#HOUSE_NUMBER_SUPPLEMENT_TEXT HOUSE_NUMBER_SUPPLEMENT_TEXT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#LANGUAGE LANGUAGE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#ORGANIZATION_NAME1 ORGANIZATION_NAME1}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#ORGANIZATION_NAME2 ORGANIZATION_NAME2}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#ORGANIZATION_NAME3 ORGANIZATION_NAME3}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#ORGANIZATION_NAME4 ORGANIZATION_NAME4}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#PERSON_FAMILY_NAME PERSON_FAMILY_NAME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#PERSON_GIVEN_NAME PERSON_GIVEN_NAME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#PO_BOX PO_BOX}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#PO_BOX_DEVIATING_CITY_NAME PO_BOX_DEVIATING_CITY_NAME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#PO_BOX_DEVIATING_COUNTRY PO_BOX_DEVIATING_COUNTRY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#PO_BOX_DEVIATING_REGION PO_BOX_DEVIATING_REGION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#PO_BOX_IS_WITHOUT_NUMBER PO_BOX_IS_WITHOUT_NUMBER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#PO_BOX_LOBBY_NAME PO_BOX_LOBBY_NAME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#PO_BOX_POSTAL_CODE PO_BOX_POSTAL_CODE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#POSTAL_CODE POSTAL_CODE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#PRFRD_COMM_MEDIUM_TYPE PRFRD_COMM_MEDIUM_TYPE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#REGION REGION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#SECONDARY_REGION SECONDARY_REGION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#SECONDARY_REGION_NAME SECONDARY_REGION_NAME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#STREET_NAME STREET_NAME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#STREET_PREFIX_NAME1 STREET_PREFIX_NAME1}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#STREET_PREFIX_NAME2 STREET_PREFIX_NAME2}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#STREET_SUFFIX_NAME1 STREET_SUFFIX_NAME1}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#STREET_SUFFIX_NAME2 STREET_SUFFIX_NAME2}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#TAX_JURISDICTION TAX_JURISDICTION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#TERTIARY_REGION TERTIARY_REGION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#TERTIARY_REGION_NAME TERTIARY_REGION_NAME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#TRANSPORT_ZONE TRANSPORT_ZONE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BPIntlAddressVersion#VILLAGE_NAME VILLAGE_NAME}</li>
 * </ul>
 * 
 */
public interface BPIntlAddressVersionSelectable
    extends EntitySelectable<BPIntlAddressVersion>
{


}
