
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.selectable;

import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BuPaAddressUsage;


/**
 * Interface to enable OData entity selectors for {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BuPaAddressUsage BuPaAddressUsage}. This interface is used by {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.field.BuPaAddressUsageField BuPaAddressUsageField} and {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.link.BuPaAddressUsageLink BuPaAddressUsageLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BuPaAddressUsage#BUSINESS_PARTNER BUSINESS_PARTNER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BuPaAddressUsage#VALIDITY_END_DATE VALIDITY_END_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BuPaAddressUsage#ADDRESS_USAGE ADDRESS_USAGE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BuPaAddressUsage#ADDRESS_ID ADDRESS_ID}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BuPaAddressUsage#VALIDITY_START_DATE VALIDITY_START_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BuPaAddressUsage#STANDARD_USAGE STANDARD_USAGE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.BuPaAddressUsage#AUTHORIZATION_GROUP AUTHORIZATION_GROUP}</li>
 * </ul>
 * 
 */
public interface BuPaAddressUsageSelectable
    extends EntitySelectable<BuPaAddressUsage>
{


}
