
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.selectable;

import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustAddrDepdntExtIdentifier;


/**
 * Interface to enable OData entity selectors for {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustAddrDepdntExtIdentifier CustAddrDepdntExtIdentifier}. This interface is used by {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.field.CustAddrDepdntExtIdentifierField CustAddrDepdntExtIdentifierField} and {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.link.CustAddrDepdntExtIdentifierLink CustAddrDepdntExtIdentifierLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustAddrDepdntExtIdentifier#CUSTOMER CUSTOMER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustAddrDepdntExtIdentifier#ADDRESS_ID ADDRESS_ID}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustAddrDepdntExtIdentifier#CUSTOMER_EXTERNAL_REF_ID CUSTOMER_EXTERNAL_REF_ID}</li>
 * </ul>
 * 
 */
public interface CustAddrDepdntExtIdentifierSelectable
    extends EntitySelectable<CustAddrDepdntExtIdentifier>
{


}
