
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.selectable;

import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea;


/**
 * Interface to enable OData entity selectors for {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea CustomerSalesArea}. This interface is used by {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.field.CustomerSalesAreaField CustomerSalesAreaField} and {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.link.CustomerSalesAreaLink CustomerSalesAreaLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#CUSTOMER CUSTOMER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#SALES_ORGANIZATION SALES_ORGANIZATION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#DISTRIBUTION_CHANNEL DISTRIBUTION_CHANNEL}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#DIVISION DIVISION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#ACCOUNT_BY_CUSTOMER ACCOUNT_BY_CUSTOMER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#AUTHORIZATION_GROUP AUTHORIZATION_GROUP}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#BILLING_IS_BLOCKED_FOR_CUSTOMER BILLING_IS_BLOCKED_FOR_CUSTOMER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#COMPLETE_DELIVERY_IS_DEFINED COMPLETE_DELIVERY_IS_DEFINED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#CREDIT_CONTROL_AREA CREDIT_CONTROL_AREA}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#CURRENCY CURRENCY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#CUST_IS_RLVT_FOR_SETTLMT_MGMT CUST_IS_RLVT_FOR_SETTLMT_MGMT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#CUSTOMER_ABC_CLASSIFICATION CUSTOMER_ABC_CLASSIFICATION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#CUSTOMER_ACCOUNT_ASSIGNMENT_GROUP CUSTOMER_ACCOUNT_ASSIGNMENT_GROUP}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#CUSTOMER_GROUP CUSTOMER_GROUP}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#CUSTOMER_IS_REBATE_RELEVANT CUSTOMER_IS_REBATE_RELEVANT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#CUSTOMER_PAYMENT_TERMS CUSTOMER_PAYMENT_TERMS}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#CUSTOMER_PRICE_GROUP CUSTOMER_PRICE_GROUP}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#CUSTOMER_PRICING_PROCEDURE CUSTOMER_PRICING_PROCEDURE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#CUST_PROD_PROPOSAL_PROCEDURE CUST_PROD_PROPOSAL_PROCEDURE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#DELIVERY_IS_BLOCKED_FOR_CUSTOMER DELIVERY_IS_BLOCKED_FOR_CUSTOMER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#DELIVERY_PRIORITY DELIVERY_PRIORITY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#INCOTERMS_CLASSIFICATION INCOTERMS_CLASSIFICATION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#INCOTERMS_LOCATION2 INCOTERMS_LOCATION2}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#INCOTERMS_VERSION INCOTERMS_VERSION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#INCOTERMS_LOCATION1 INCOTERMS_LOCATION1}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#INCOTERMS_SUP_CHN_LOC1_ADDL_UUID INCOTERMS_SUP_CHN_LOC1_ADDL_UUID}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#INCOTERMS_SUP_CHN_LOC2_ADDL_UUID INCOTERMS_SUP_CHN_LOC2_ADDL_UUID}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#INCOTERMS_SUP_CHN_DVTG_LOC_ADDL_UUID INCOTERMS_SUP_CHN_DVTG_LOC_ADDL_UUID}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#DELETION_INDICATOR DELETION_INDICATOR}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#INCOTERMS_TRANSFER_LOCATION INCOTERMS_TRANSFER_LOCATION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#INSP_SBST_HAS_NO_TIME_OR_QUANTITY INSP_SBST_HAS_NO_TIME_OR_QUANTITY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#INVOICE_DATE INVOICE_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#ITEM_ORDER_PROBABILITY_IN_PERCENT ITEM_ORDER_PROBABILITY_IN_PERCENT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#MANUAL_INVOICE_MAINT_IS_RELEVANT MANUAL_INVOICE_MAINT_IS_RELEVANT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#MAX_NMBR_OF_PARTIAL_DELIVERY MAX_NMBR_OF_PARTIAL_DELIVERY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#ORDER_COMBINATION_IS_ALLOWED ORDER_COMBINATION_IS_ALLOWED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#ORDER_IS_BLOCKED_FOR_CUSTOMER ORDER_IS_BLOCKED_FOR_CUSTOMER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#OVERDELIV_TOLRTD_LMT_RATIO_IN_PCT OVERDELIV_TOLRTD_LMT_RATIO_IN_PCT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#PARTIAL_DELIVERY_IS_ALLOWED PARTIAL_DELIVERY_IS_ALLOWED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#PRICE_LIST_TYPE PRICE_LIST_TYPE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#PRODUCT_UNIT_GROUP PRODUCT_UNIT_GROUP}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#PROOF_OF_DELIVERY_TIME_VALUE PROOF_OF_DELIVERY_TIME_VALUE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#SALES_GROUP SALES_GROUP}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#SALES_ITEM_PROPOSAL SALES_ITEM_PROPOSAL}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#SALES_OFFICE SALES_OFFICE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#SHIPPING_CONDITION SHIPPING_CONDITION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#SLS_DOC_IS_RLVT_FOR_PROOF_OF_DELIV SLS_DOC_IS_RLVT_FOR_PROOF_OF_DELIV}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#SLS_UNLMTD_OVRDELIV_IS_ALLWD SLS_UNLMTD_OVRDELIV_IS_ALLWD}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#SUPPLYING_PLANT SUPPLYING_PLANT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#SALES_DISTRICT SALES_DISTRICT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#UNDERDELIV_TOLRTD_LMT_RATIO_IN_PCT UNDERDELIV_TOLRTD_LMT_RATIO_IN_PCT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#INVOICE_LIST_SCHEDULE INVOICE_LIST_SCHEDULE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#EXCHANGE_RATE_TYPE EXCHANGE_RATE_TYPE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#ADDITIONAL_CUSTOMER_GROUP1 ADDITIONAL_CUSTOMER_GROUP1}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#ADDITIONAL_CUSTOMER_GROUP2 ADDITIONAL_CUSTOMER_GROUP2}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#ADDITIONAL_CUSTOMER_GROUP3 ADDITIONAL_CUSTOMER_GROUP3}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#ADDITIONAL_CUSTOMER_GROUP4 ADDITIONAL_CUSTOMER_GROUP4}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#ADDITIONAL_CUSTOMER_GROUP5 ADDITIONAL_CUSTOMER_GROUP5}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#PAYMENT_GUARANTEE_PROCEDURE PAYMENT_GUARANTEE_PROCEDURE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#CUSTOMER_ACCOUNT_GROUP CUSTOMER_ACCOUNT_GROUP}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#TO_PARTNER_FUNCTION TO_PARTNER_FUNCTION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#TO_SALES_AREA_TAX TO_SALES_AREA_TAX}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#TO_SALES_AREA_TEXT TO_SALES_AREA_TEXT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesArea#TO_SLS_AREA_ADDR_DEPDNT_INFO TO_SLS_AREA_ADDR_DEPDNT_INFO}</li>
 * </ul>
 * 
 */
public interface CustomerSalesAreaSelectable
    extends EntitySelectable<CustomerSalesArea>
{


}
